### ISSUE TITLE
Fallback from https to http? Failing silently

### ISSUE THREAD

**Issue by mandrewstuart** [fluttercommunity/flutter_webview_plugin#429]
Is there a way to make a request to an HTTPS site fallback to HTTP? When I try accessing a server with HTTPS that only exists in HTTP, I don't get anything from onHttpError or onStateChange.

Thanks!

**Comment by charafau** [comment]
Is it android related only? I think it's because of android changed policy on from lollipop (api 21) and you need to specify that you want to allow that explicitly.

https://stackoverflow.com/questions/28626433/android-webview-blocks-redirect-from-https-to-http

it's not implemented now in plugin, but could be added. PRs welcome, but first please create an issue.

**Comment by mandrewstuart** [comment]
Thanks! I ended up sending an extra request to sites before navigating to them when the protocol is missing. I'm planning to load the data from the first request into the webview from the String output but I have to figure out how to get the cookies from the corresponding domain first.
